### ISSUE TITLE
Add Animations

### ISSUE THREAD

**Issue by majuro16** [aliengine/aliengine.github.io#6]
add animations

**Comment by francescobianco** [comment]
The wave are not visibile by default, it require to scroll down a little bit.
![Screenshot from 2020-09-23 16-41-54](https://user-images.githubusercontent.com/472171/94028113-defc2680-fdbb-11ea-8e3c-6b1199971843.png)

is possible move on top waves in a way it is visible without scroll? @majuro16 it make sense?

**Comment by majuro16** [comment]
certainly, done and pushed
